name: parastell_env
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - pip=24.0
  - numpy
  - scipy
  - scikit-learn
  - cadquery
  - moab==5.5.0[build=nompi_tempest_*]
  - ca-certificates
  - certifi
  - openssl
  - matplotlib
  - gmsh
  - python-gmsh
  - pip:
      - cad_to_dagmc<0.6
      - netcdf4
      - pyyaml
      - pytest