name: Build & Publish docker image for ParaStell CI

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker_publish.yml'

jobs:
  build-dependency-img:
    runs-on: ubuntu-latest

    name: Installing Dependencies and ParaStell
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, Test, and Push ParaStell
        id: build-parastell
        uses: docker/build-push-action@v5
        with:
          cache-from: type=registry,ref=ghcr.io/svalinn/parastell:ci-layer-cache
          cache-to: type=registry,ref=ghcr.io/svalinn/parastell:ci-layer-cache,mode=max
          file: Dockerfile
          push: true
          target: parastell-deps
          tags: ghcr.io/svalinn/parstell-ci

  test-dependency-img:
    needs: build-dependency-img
    runs-on: ubuntu-latest
    container: ghcr.io/svalinn/parstell-ci

    name: Testing CI image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: populate environment
        run: |
          echo "rlmSERVER=${{ secrets.RLMSERVER }}" >> "$GITHUB_ENV"
          echo "rlmPASSWD=${{ secrets.RLMPASSWORD}}" >> "$GITHUB_ENV"

      - name: test secrets
        run: |
          conda activate parastell_env
          sed -e "s/@SERVER@/${rlmSERVER}/" -e "s/@PASSWORD@/${rlmPASSWD}/" /opt/Coreform-Cubit-2023.11/bin/licenses/rlmcloud.in > /opt/Coreform-Cubit-2023.11/bin/licenses/rlmcloud.lic
          cd tests
          pytest -v .






